title: Sharpen Live
description: >
  Documentation and resources for the Sharpen Live project.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  refactor/items/backend-consolidation
  refactor/items/backend-structure
